-- Clear existing geographic data
DELETE FROM public.snapshot_cities;
DELETE FROM public.snapshot_countries;
DELETE FROM public.snapshot_geographic_regions;

-- Insert the comprehensive regional structure
INSERT INTO public.snapshot_geographic_regions (name, slug) VALUES
('Asia Pacific', 'asia-pacific'),
('Emerging Asia', 'emerging-asia'),
('Europe', 'europe'),
('Latin America', 'latin-america'),
('Middle East & Africa', 'middle-east-africa'),
('North America', 'north-america');

-- Insert all countries with their proper regional associations
WITH region_ids AS (
  SELECT id, slug FROM public.snapshot_geographic_regions
)
INSERT INTO public.snapshot_countries (region_id, name, slug) VALUES
-- Asia Pacific
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Australia', 'australia'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Brunei', 'brunei'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Cook Islands', 'cook-islands'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Fiji', 'fiji'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'French Polynesia', 'french-polynesia'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Hong Kong', 'hong-kong'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Japan', 'japan'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Kiribati', 'kiribati'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Macau', 'macau'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Marshall Islands', 'marshall-islands'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Micronesia', 'micronesia'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Nauru', 'nauru'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'New Caledonia', 'new-caledonia'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'New Zealand', 'new-zealand'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Palau', 'palau'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Papua New Guinea', 'papua-new-guinea'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Samoa', 'samoa'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Singapore', 'singapore'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Solomon Islands', 'solomon-islands'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'South Korea', 'south-korea'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Taiwan', 'taiwan'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Tonga', 'tonga'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Tuvalu', 'tuvalu'),
((SELECT id FROM region_ids WHERE slug = 'asia-pacific'), 'Vanuatu', 'vanuatu'),

-- Emerging Asia
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Afghanistan', 'afghanistan'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Bangladesh', 'bangladesh'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Bhutan', 'bhutan'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Cambodia', 'cambodia'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'China', 'china'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'East Timor (Timor-Leste)', 'east-timor-timor-leste'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'India', 'india'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Indonesia', 'indonesia'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Kazakhstan', 'kazakhstan'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Kyrgyzstan', 'kyrgyzstan'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Laos', 'laos'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Malaysia', 'malaysia'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Maldives', 'maldives'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Mongolia', 'mongolia'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Myanmar', 'myanmar'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Nepal', 'nepal'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'North Korea', 'north-korea'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Pakistan', 'pakistan'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Philippines', 'philippines'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Sri Lanka', 'sri-lanka'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Tajikistan', 'tajikistan'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Thailand', 'thailand'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Turkmenistan', 'turkmenistan'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Uzbekistan', 'uzbekistan'),
((SELECT id FROM region_ids WHERE slug = 'emerging-asia'), 'Vietnam', 'vietnam'),

-- Europe
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Albania', 'albania'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Andorra', 'andorra'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Armenia', 'armenia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Austria', 'austria'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Azerbaijan', 'azerbaijan'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Belarus', 'belarus'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Belgium', 'belgium'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Bosnia and Herzegovina', 'bosnia-and-herzegovina'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Bulgaria', 'bulgaria'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Croatia', 'croatia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Cyprus', 'cyprus'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Czech Republic', 'czech-republic'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Denmark', 'denmark'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Estonia', 'estonia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Finland', 'finland'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'France', 'france'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Georgia', 'georgia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Germany', 'germany'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Greece', 'greece'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Hungary', 'hungary'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Iceland', 'iceland'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Ireland', 'ireland'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Italy', 'italy'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Kosovo', 'kosovo'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Latvia', 'latvia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Liechtenstein', 'liechtenstein'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Lithuania', 'lithuania'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Luxembourg', 'luxembourg'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Malta', 'malta'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Moldova', 'moldova'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Monaco', 'monaco'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Montenegro', 'montenegro'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Netherlands', 'netherlands'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'North Macedonia', 'north-macedonia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Norway', 'norway'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Poland', 'poland'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Portugal', 'portugal'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Romania', 'romania'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Russia', 'russia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'San Marino', 'san-marino'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Serbia', 'serbia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Slovakia', 'slovakia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Slovenia', 'slovenia'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Spain', 'spain'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Sweden', 'sweden'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Switzerland', 'switzerland'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Turkey', 'turkey'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Ukraine', 'ukraine'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'United Kingdom', 'united-kingdom'),
((SELECT id FROM region_ids WHERE slug = 'europe'), 'Vatican City (Holy See)', 'vatican-city-holy-see'),

-- Latin America
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Antigua and Barbuda', 'antigua-and-barbuda'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Anguilla', 'anguilla'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Argentina', 'argentina'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Aruba', 'aruba'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Bahamas', 'bahamas'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Barbados', 'barbados'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Belize', 'belize'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Bermuda', 'bermuda'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Bolivia', 'bolivia'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Brazil', 'brazil'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Cayman Islands', 'cayman-islands'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Chile', 'chile'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Colombia', 'colombia'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Costa Rica', 'costa-rica'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Cuba', 'cuba'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Curaçao', 'curacao'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Dominica', 'dominica'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Dominican Republic', 'dominican-republic'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Ecuador', 'ecuador'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'El Salvador', 'el-salvador'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Grenada', 'grenada'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Guatemala', 'guatemala'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Guyana', 'guyana'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Haiti', 'haiti'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Honduras', 'honduras'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Jamaica', 'jamaica'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Montserrat', 'montserrat'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Nicaragua', 'nicaragua'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Panama', 'panama'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Paraguay', 'paraguay'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Peru', 'peru'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Puerto Rico', 'puerto-rico'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Saint Kitts and Nevis', 'saint-kitts-and-nevis'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Saint Lucia', 'saint-lucia'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Saint Vincent and the Grenadines', 'saint-vincent-and-the-grenadines'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Sint Maarten', 'sint-maarten'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Suriname', 'suriname'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Trinidad and Tobago', 'trinidad-and-tobago'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Turks and Caicos Islands', 'turks-and-caicos-islands'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Uruguay', 'uruguay'),
((SELECT id FROM region_ids WHERE slug = 'latin-america'), 'Venezuela', 'venezuela'),

-- Middle East & Africa
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Algeria', 'algeria'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Angola', 'angola'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Bahrain', 'bahrain'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Benin', 'benin'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Botswana', 'botswana'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Burkina Faso', 'burkina-faso'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Burundi', 'burundi'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Cameroon', 'cameroon'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Cape Verde (Cabo Verde)', 'cape-verde-cabo-verde'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Central African Republic', 'central-african-republic'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Chad', 'chad'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Comoros', 'comoros'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Congo', 'congo'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Djibouti', 'djibouti'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'DR Congo', 'dr-congo'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Egypt', 'egypt'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Equatorial Guinea', 'equatorial-guinea'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Eritrea', 'eritrea'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Eswatini', 'eswatini'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Ethiopia', 'ethiopia'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Gabon', 'gabon'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Gambia', 'gambia'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Ghana', 'ghana'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Guinea', 'guinea'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Guinea-Bissau', 'guinea-bissau'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Iran', 'iran'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Iraq', 'iraq'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Israel', 'israel'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Ivory Coast (Côte d''Ivoire)', 'ivory-coast-cote-d-ivoire'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Jordan', 'jordan'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Kenya', 'kenya'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Kuwait', 'kuwait'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Lebanon', 'lebanon'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Lesotho', 'lesotho'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Liberia', 'liberia'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Libya', 'libya'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Madagascar', 'madagascar'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Malawi', 'malawi'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Mali', 'mali'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Mauritania', 'mauritania'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Mauritius', 'mauritius'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Morocco', 'morocco'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Mozambique', 'mozambique'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Namibia', 'namibia'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Niger', 'niger'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Nigeria', 'nigeria'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Oman', 'oman'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Palestine', 'palestine'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Qatar', 'qatar'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Rwanda', 'rwanda'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'São Tomé and Príncipe', 'sao-tome-and-principe'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Saudi Arabia', 'saudi-arabia'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Senegal', 'senegal'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Seychelles', 'seychelles'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Sierra Leone', 'sierra-leone'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Somalia', 'somalia'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'South Africa', 'south-africa'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'South Sudan', 'south-sudan'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Sudan', 'sudan'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Syria', 'syria'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Tanzania', 'tanzania'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Togo', 'togo'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Tunisia', 'tunisia'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'UAE (United Arab Emirates)', 'uae-united-arab-emirates'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Uganda', 'uganda'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Yemen', 'yemen'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Zambia', 'zambia'),
((SELECT id FROM region_ids WHERE slug = 'middle-east-africa'), 'Zimbabwe', 'zimbabwe'),

-- North America
((SELECT id FROM region_ids WHERE slug = 'north-america'), 'Canada', 'canada'),
((SELECT id FROM region_ids WHERE slug = 'north-america'), 'Greenland', 'greenland'),
((SELECT id FROM region_ids WHERE slug = 'north-america'), 'Mexico', 'mexico'),
((SELECT id FROM region_ids WHERE slug = 'north-america'), 'United States', 'united-states');