-- First, let's create companies that don't exist yet
INSERT INTO public.companies (name, slug, company_type, published, featured) VALUES
('Amazon.com, Inc.', 'amazon-com-inc', 'enterprise', true, true),
('Thrive Global Holdings, Inc.', 'thrive-global-holdings-inc', 'startup', true, false),
('Imagine Marketing Private Limited', 'imagine-marketing-private-limited', 'startup', true, false),
('European Commission', 'european-commission', 'government', true, false),
('HubSpot, Inc.', 'hubspot-inc', 'enterprise', true, true),
('Silicon Clocks', 'silicon-clocks', 'startup', true, false),
('Inc42', 'inc42', 'media', true, false),
('Lenskart Solutions Private Limited', 'lenskart-solutions-private-limited', 'startup', true, true),
('Flipkart Internet Private Limited', 'flipkart-internet-private-limited', 'enterprise', true, true),
('Nu Pagamentos S.A.', 'nu-pagamentos-sa', 'fintech', true, true),
('Meta Inc.', 'meta-inc', 'enterprise', true, true),
('A&A Dukaan Financial Services Private Limited', 'aa-dukaan-financial-services-private-limited', 'fintech', true, false),
('Skift', 'skift', 'media', true, false),
('JUUL Labs, Inc.', 'juul-labs-inc', 'startup', true, false),
('Under Technologies Inc.', 'under-technologies-inc', 'startup', true, false),
('LinkedIn Corporation', 'linkedin-corporation', 'enterprise', true, true),
('Mandalay Sports Media', 'mandalay-sports-media', 'media', true, false),
('Uber, Inc.', 'uber-inc', 'enterprise', true, true),
('Rent the Runway, Inc.', 'rent-the-runway-inc', 'startup', true, true),
('Tod''s Retail India Private Ltd', 'tods-retail-india-private-ltd', 'retail', true, false),
('Airbnb, Inc.', 'airbnb-inc', 'enterprise', true, true),
('Starschema Ltd.', 'starschema-ltd', 'startup', true, false),
('NVIDIA Corporation', 'nvidia-corporation', 'enterprise', true, true),
('Canva Pty Ltd', 'canva-pty-ltd', 'startup', true, true),
('Wonder', 'wonder', 'startup', true, false),
('Booksy Holdings, Inc.', 'booksy-holdings-inc', 'startup', true, false),
('Hint Inc.', 'hint-inc', 'startup', true, false),
('DailyWorth', 'dailyworth', 'fintech', true, false),
('Platzi Inc.', 'platzi-inc', 'edtech', true, false),
('InMobi Pte Ltd', 'inmobi-pte-ltd', 'startup', true, false),
('Indago', 'indago', 'startup', true, false),
('Jibble Tech Sdn Bhd', 'jibble-tech-sdn-bhd', 'startup', true, false),
('Fluree, PBC', 'fluree-pbc', 'startup', true, false),
('The King', 'the-king', 'nonprofit', true, false),
('Geekpark', 'geekpark', 'media', true, false),
('JAND, Inc.', 'jand-inc', 'startup', true, false),
('Hugging Face, Inc.', 'hugging-face-inc', 'startup', true, true),
('ATET', 'atet', 'enterprise', true, false),
('Smile Telecoms Holdings Limited', 'smile-telecoms-holdings-limited', 'telecom', true, false),
('Valores Corporativos Softtek, S.A. de C.V.', 'valores-corporativos-softtek-sa-de-cv', 'enterprise', true, false),
('Recruiter.com', 'recruiter-com', 'startup', true, false),
('Konflake Tech Pvt. Ltd.', 'konflake-tech-pvt-ltd', 'startup', true, false),
('Snowflake Inc.', 'snowflake-inc', 'enterprise', true, true),
('GlaxoSmithKline''s Cell Map Unit', 'glaxosmithklines-cell-map-unit', 'enterprise', true, false),
('Pyramid Analytics BV', 'pyramid-analytics-bv', 'startup', true, false),
('Netflix, Inc.', 'netflix-inc', 'enterprise', true, true),
('Palo Alto Networks, Inc.', 'palo-alto-networks-inc', 'enterprise', true, true),
('NDTV Networks', 'ndtv-networks', 'media', true, false),
('Capgeminis IBX Business Network', 'capgeminis-ibx-business-network', 'enterprise', true, false),
('Amplitude Inc.', 'amplitude-inc', 'startup', true, false),
('CloudEnablers Inc.', 'cloudenablers-inc', 'startup', true, false),
('Boston Consulting Group, Inc.''s SOURCE AI Technology', 'boston-consulting-group-incs-source-ai-technology', 'consulting', true, false),
('iFood.com Agncia de Restaurantes Online S.A.', 'ifood-com-agncia-de-restaurantes-online-sa', 'startup', true, false),
('Smartly.io Solutions Oy', 'smartly-io-solutions-oy', 'startup', true, false),
('LegalZoom.com Inc', 'legalzoom-com-inc', 'startup', true, false),
('Workday, Inc.', 'workday-inc', 'enterprise', true, true),
('Paytm Payments Bank Ltd.', 'paytm-payments-bank-ltd', 'fintech', true, true),
('Fashnear Technologies Private Limited', 'fashnear-technologies-private-limited', 'startup', true, false),
('Devnet', 'devnet', 'startup', true, false),
('Click', 'click', 'startup', true, false),
('BuzzFeed, Inc.', 'buzzfeed-inc', 'media', true, false),
('Shutterstock', 'shutterstock', 'enterprise', true, true),
('Okera, Inc.', 'okera-inc', 'startup', true, false),
('37signals, LLC', '37signals-llc', 'startup', true, false),
('Yatra Online Pvt Ltd', 'yatra-online-pvt-ltd', 'startup', true, false),
('Affirm, Inc.', 'affirm-inc', 'fintech', true, true),
('Epocal Inc.', 'epocal-inc', 'startup', true, false),
('Supplying Demand Inc.', 'supplying-demand-inc', 'startup', true, false),
('SAP SE', 'sap-se', 'enterprise', true, true),
('Altigreen Propulsion Labs Pvt. Ltd.', 'altigreen-propulsion-labs-pvt-ltd', 'startup', true, false),
('Peloton Interactive, Inc.', 'peloton-interactive-inc', 'startup', true, false),
('Atomberg Technology Pvt Ltd', 'atomberg-technology-pvt-ltd', 'startup', true, false),
('Odoo SA', 'odoo-sa', 'startup', true, false),
('Gartner, Inc.', 'gartner-inc', 'enterprise', true, true),
('YouTube', 'youtube', 'enterprise', true, true),
('Chowbotics', 'chowbotics', 'startup', true, false),
('Bundl Technologies Private Limited', 'bundl-technologies-private-limited', 'startup', true, false),
('HackerRank', 'hackerrank', 'startup', true, false),
('Plexo Capital Management LLC', 'plexo-capital-management-llc', 'investment', true, false),
('ModelSquared', 'modelsquared', 'startup', true, false),
('Ujjivan Financial Services Pvt Ltd', 'ujjivan-financial-services-pvt-ltd', 'fintech', true, false),
('TikTok Inc.', 'tiktok-inc', 'enterprise', true, true),
('Satispay S.p.A. Group', 'satispay-spa-group', 'fintech', true, false),
('Sorting Hat Technologies Private Limited', 'sorting-hat-technologies-private-limited', 'edtech', true, false),
('Planet Labs Inc.', 'planet-labs-inc', 'startup', true, false),
('Kodiak Robotics, Inc.', 'kodiak-robotics-inc', 'startup', true, false),
('Orange Group', 'orange-group', 'telecom', true, false),
('IKAS Teknoloji A.S.', 'ikas-teknoloji-as', 'startup', true, false),
('BioNTech SE', 'biontech-se', 'biotech', true, true),
('Squats Fitness Private Limited', 'squats-fitness-private-limited', 'startup', true, false),
('ImmaculateBites Pvt. Ltd.', 'immaculatebites-pvt-ltd', 'startup', true, false),
('Tripledot Studios Limited', 'tripledot-studios-limited', 'gaming', true, false),
('Gladly Software, Inc.', 'gladly-software-inc', 'startup', true, false),
('SUSE Software Solutions Germany GmbH', 'suse-software-solutions-germany-gmbh', 'enterprise', true, false),
('CrowdStrike Holdings Inc.', 'crowdstrike-holdings-inc', 'enterprise', true, true),
('Maplebear Inc.', 'maplebear-inc', 'startup', true, false),
('Brand24 Global Inc.', 'brand24-global-inc', 'startup', true, false),
('Bewakoof Brands Private Limited', 'bewakoof-brands-private-limited', 'startup', true, false),
('PoshVine', 'poshvine', 'startup', true, false),
('GitHub, Inc.', 'github-inc', 'enterprise', true, true),
('1stdibs.com, Inc.', '1stdibs-com-inc', 'startup', true, false),
('Overtime Sports Inc.', 'overtime-sports-inc', 'startup', true, false),
('Rede Mulher Empreendedora', 'rede-mulher-empreendedora', 'nonprofit', true, false),
('Whoop, Inc.', 'whoop-inc', 'startup', true, false),
('Pray, Inc.', 'pray-inc', 'startup', true, false),
('Uptake Technologies Inc.', 'uptake-technologies-inc', 'startup', true, false),
('Truist', 'truist', 'enterprise', true, false),
('Zoom Video Communications, Inc.', 'zoom-video-communications-inc', 'enterprise', true, true),
('Armory, Inc.', 'armory-inc', 'startup', true, false),
('Anywhere Corp.', 'anywhere-corp', 'startup', true, false),
('Seamless.AI', 'seamless-ai', 'startup', true, false),
('Talabat.com', 'talabat-com', 'startup', true, false),
('GHV Advanced Care Private Limited', 'ghv-advanced-care-private-limited', 'healthcare', true, false),
('CIGNEX Technologies, Inc.', 'cignex-technologies-inc', 'startup', true, false),
('Freshworks Inc.', 'freshworks-inc', 'enterprise', true, true),
('Headspace Inc.', 'headspace-inc', 'startup', true, false),
('Zomato Private Limited', 'zomato-private-limited', 'startup', true, true),
('CloudSEK Info Security Pvt. Ltd', 'cloudsek-info-security-pvt-ltd', 'cybersecurity', true, false),
('Octave Health Group, Inc.', 'octave-health-group-inc', 'healthcare', true, false),
('Pine Labs Pvt Ltd', 'pine-labs-pvt-ltd', 'fintech', true, true),
('Siemens'' Organic Photovoltaic Research Activities', 'siemens-organic-photovoltaic-research-activities', 'enterprise', true, false),
('Getir', 'getir', 'startup', true, false),
('DocuSign, Inc.', 'docusign-inc', 'enterprise', true, true),
('Zscaler, Inc.', 'zscaler-inc', 'enterprise', true, true),
('Nokia gate5 GmbH', 'nokia-gate5-gmbh', 'enterprise', true, false),
('mLabs Software Ltda.', 'mlabs-software-ltda', 'startup', true, false),
('The Not Company', 'the-not-company', 'startup', true, false),
('Groq, Inc.', 'groq-inc', 'startup', true, true),
('BrainJuicer', 'brainjuicer', 'startup', true, false),
('Adinio Services Private Limited', 'adinio-services-private-limited', 'startup', true, false),
('Gravity Industries', 'gravity-industries', 'startup', true, false),
('Bravado Network, Inc.', 'bravado-network-inc', 'startup', true, false),
('Meio Medical', 'meio-medical', 'healthcare', true, false),
('Atlassian Pty. Ltd.', 'atlassian-pty-ltd', 'enterprise', true, true),
('Catamorphic, Co.', 'catamorphic-co', 'startup', true, false),
('Gupy Tecnologia em Recrutamento LTDA', 'gupy-tecnologia-em-recrutamento-ltda', 'startup', true, false)
ON CONFLICT (slug) DO NOTHING;

-- Now insert the people records
INSERT INTO public.people (full_name, slug, title, current_company_id, linkedin_url, published, featured) VALUES
('Andy Jassy', 'andy-jassy', 'President and CEO', (SELECT id FROM companies WHERE slug = 'amazon-com-inc'), 'http://www.linkedin.com/in/andy-jassy-8b1615', true, true),
('Arianna Huffington', 'arianna-huffington', 'Founder and CEO', (SELECT id FROM companies WHERE slug = 'thrive-global-holdings-inc'), 'http://www.linkedin.com/in/ariannahuffington', true, true),
('Aman Gupta', 'aman-gupta', 'Co Founder and CMO', (SELECT id FROM companies WHERE slug = 'imagine-marketing-private-limited'), 'http://www.linkedin.com/in/aman-gupta-7217a515', true, false),
('Ursula Der Leyen', 'ursula-der-leyen', 'President of the European Commission', (SELECT id FROM companies WHERE slug = 'european-commission'), 'http://www.linkedin.com/in/ursula-von-der-leyen', true, true),
('Dharmesh Shah', 'dharmesh-shah', 'Founder and CTO', (SELECT id FROM companies WHERE slug = 'hubspot-inc'), 'http://www.linkedin.com/in/dharmesh', true, true),
('Laszlo Bock', 'laszlo-bock', 'Co-Founder and Co-Faculty Director of the Berkeley Transformative CHRO Academy', (SELECT id FROM companies WHERE slug = 'silicon-clocks'), 'http://www.linkedin.com/in/laszlobock', true, false),
('Pooja Sareen', 'pooja-sareen', 'Cofounder & EIC', (SELECT id FROM companies WHERE slug = 'inc42'), 'http://www.linkedin.com/in/pooja-sareen-23874151', true, false),
('Peyush Bansal', 'peyush-bansal', 'Co-Founder, Chief Executive Officer', (SELECT id FROM companies WHERE slug = 'lenskart-solutions-private-limited'), 'http://www.linkedin.com/in/peyushbansal', true, true),
('Ankita Das', 'ankita-das', 'Human Resource Business Partner', (SELECT id FROM companies WHERE slug = 'flipkart-internet-private-limited'), 'http://www.linkedin.com/in/ankita-das-38445319a', true, false),
('Cristina Junqueira', 'cristina-junqueira', 'Co-Founder', (SELECT id FROM companies WHERE slug = 'nu-pagamentos-sa'), 'http://www.linkedin.com/in/cristina-junqueira-1194878', true, true),
('Clara Shih', 'clara-shih', 'SVP, Head of Business AI', (SELECT id FROM companies WHERE slug = 'meta-inc'), 'http://www.linkedin.com/in/clarashih', true, true),
('Adhil Shetty', 'adhil-shetty', 'CEO', (SELECT id FROM companies WHERE slug = 'aa-dukaan-financial-services-private-limited'), 'http://www.linkedin.com/in/adhilshetty', true, false),
('Rafat Ali', 'rafat-ali', 'CEO/Founder', (SELECT id FROM companies WHERE slug = 'skift'), 'http://www.linkedin.com/in/rafatali', true, false),
('Maros Sefcovic', 'maros-sefcovic', 'European Commission Executive Vice-President', (SELECT id FROM companies WHERE slug = 'european-commission'), 'http://www.linkedin.com/in/marossefcovic', true, false),
('Nikhil Bhat', 'nikhil-bhat', 'Vice President Product & Hardware Engineering', (SELECT id FROM companies WHERE slug = 'juul-labs-inc'), 'http://www.linkedin.com/in/nikhildbhat', true, false),
('Natalie Riso', 'natalie-riso', 'Director, Head of Startups and Strategic Partnerships', (SELECT id FROM companies WHERE slug = 'under-technologies-inc'), 'http://www.linkedin.com/in/natalieriso', true, false),
('Katie Carroll', 'katie-carroll', 'Director, Global Head of Community Programs', (SELECT id FROM companies WHERE slug = 'linkedin-corporation'), 'http://www.linkedin.com/in/kredcarroll', true, false),
('Peter Guber', 'peter-guber', 'Chairman and CEO', (SELECT id FROM companies WHERE slug = 'mandalay-sports-media'), 'http://www.linkedin.com/in/peterguber', true, false),
('Dara Khosrowshahi', 'dara-khosrowshahi', 'CEO', (SELECT id FROM companies WHERE slug = 'uber-inc'), 'http://www.linkedin.com/in/dara-khosrowshahi-70949862', true, true),
('Jennifer Hyman', 'jennifer-hyman', 'CEO, Co-Founder and Chair of the Board', (SELECT id FROM companies WHERE slug = 'rent-the-runway-inc'), 'http://www.linkedin.com/in/jennifer-hyman-14970017', true, true),
('Michela Gioacchini', 'michela-gioacchini', 'Head of Sustainability & Corporate Social Responsibility', (SELECT id FROM companies WHERE slug = 'tods-retail-india-private-ltd'), 'http://www.linkedin.com/in/michelagioacchini318', true, false),
('Tai Tran', 'tai-tran', 'Head of Strategy & Operations', (SELECT id FROM companies WHERE slug = 'airbnb-inc'), 'http://www.linkedin.com/in/taictran', true, false),
('Daniel Roth', 'daniel-roth', 'Editor In Chief, VP of Content Development', (SELECT id FROM companies WHERE slug = 'linkedin-corporation'), 'http://www.linkedin.com/in/danielroth1', true, false),
('Vijayakumar C', 'vijayakumar-c', 'Chief Executive Officer', (SELECT id FROM companies WHERE slug = 'starschema-ltd'), 'http://www.linkedin.com/in/vijayakumar-c-hcl', true, false),
('Jensen Huang', 'jensen-huang', 'Founder and CEO', (SELECT id FROM companies WHERE slug = 'nvidia-corporation'), 'http://www.linkedin.com/in/jensen-huang-109a798b', true, true),
('Melanie Perkins', 'melanie-perkins', 'CEO & Co-founder', (SELECT id FROM companies WHERE slug = 'canva-pty-ltd'), '', true, true),
('Marc Lore', 'marc-lore', 'Founder & CEO', (SELECT id FROM companies WHERE slug = 'wonder'), '', true, false),
('Kristina Salen', 'kristina-salen', 'Chief Financial Officer', (SELECT id FROM companies WHERE slug = 'booksy-holdings-inc'), '', true, false),
('Kara Goldin', 'kara-goldin', 'Founder and CEO', (SELECT id FROM companies WHERE slug = 'hint-inc'), '', true, false),
('Jean Chatzky', 'jean-chatzky', 'CEO and Co-Founder', (SELECT id FROM companies WHERE slug = 'dailyworth'), '', true, false),
('Freddy Vega', 'freddy-vega', 'CEO', (SELECT id FROM companies WHERE slug = 'platzi-inc'), '', true, false),
('Naveen Tewari', 'naveen-tewari', 'Founder & CEO', (SELECT id FROM companies WHERE slug = 'inmobi-pte-ltd'), '', true, false),
('Adrian Gonzalez', 'adrian-gonzalez', 'Founder', (SELECT id FROM companies WHERE slug = 'indago'), '', true, false),
('Asim Qureshi', 'asim-qureshi', 'CEO', (SELECT id FROM companies WHERE slug = 'jibble-tech-sdn-bhd'), '', true, false),
('Andrew Filipowski', 'andrew-filipowski', 'Co Founder', (SELECT id FROM companies WHERE slug = 'fluree-pbc'), '', true, false),
('Bernice King', 'bernice-king', 'Chief Executive Officer', (SELECT id FROM companies WHERE slug = 'the-king'), '', true, false),
('Adam Biddlecombe', 'adam-biddlecombe', 'Head of Brand - Mindstream', (SELECT id FROM companies WHERE slug = 'hubspot-inc'), '', true, false),
('Jack Zhang', 'jack-zhang', 'Founder & President', (SELECT id FROM companies WHERE slug = 'geekpark'), '', true, false),
('Neil Blumenthal', 'neil-blumenthal', 'Co-Founder and Co-CEO', (SELECT id FROM companies WHERE slug = 'jand-inc'), '', true, false),
('Julien Chaumond', 'julien-chaumond', 'Co-founder', (SELECT id FROM companies WHERE slug = 'hugging-face-inc'), '', true, true),
('Jennifer Buskirk', 'jennifer-buskirk', 'Head of Business Operations', (SELECT id FROM companies WHERE slug = 'atet'), '', true, false),
('Akinola Alayoku', 'akinola-alayoku', 'Chief Technical Officer', (SELECT id FROM companies WHERE slug = 'smile-telecoms-holdings-limited'), '', true, false),
('Amy Miller', 'amy-miller', 'Head of Category Management', (SELECT id FROM companies WHERE slug = 'amazon-com-inc'), '', true, false),
('Carlos Funes', 'carlos-funes', 'Global Head of Banking and Financial Services', (SELECT id FROM companies WHERE slug = 'valores-corporativos-softtek-sa-de-cv'), '', true, false),
('Matt Charney', 'matt-charney', 'Editor in Chief at Recruiter.com | Chief Marketing Officer & Co-Founder', (SELECT id FROM companies WHERE slug = 'recruiter-com'), '', true, false),
('Ragini Das', 'ragini-das', 'Co-Founder & Chief Cheerleader', (SELECT id FROM companies WHERE slug = 'konflake-tech-pvt-ltd'), '', true, false),
('Roopal Shah', 'roopal-shah', 'Chief Executive Officer', (SELECT id FROM companies WHERE slug = 'snowflake-inc'), '', true, false),
('Emma Walmsley', 'emma-walmsley', 'CEO', (SELECT id FROM companies WHERE slug = 'glaxosmithklines-cell-map-unit'), '', true, false),
('Joe Beaubien', 'joe-beaubien', 'Vice President Global Solution Engineering', (SELECT id FROM companies WHERE slug = 'pyramid-analytics-bv'), '', true, false),
('Anushree Kothari', 'anushree-kothari', 'Head of Talent Acquisition - India (Netflix & Scanline VFX)', (SELECT id FROM companies WHERE slug = 'netflix-inc'), '', true, false),
('Nikesh Arora', 'nikesh-arora', 'Chairman CEO', (SELECT id FROM companies WHERE slug = 'palo-alto-networks-inc'), 'http://www.linkedin.com/in/nikesh-arora-02894670', true, true);