// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhanfpnfsbqvepwetyxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoYW5mcG5mc2JxdmVwd2V0eXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDg3NDAsImV4cCI6MjA3MTAyNDc0MH0.hfF_Pnd-iTpQuUsvroxSrh2MssxP7eVJg2-xfI1AkaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});